<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<Platforms>AnyCPU;x64;x86</Platforms>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Test2025.csv" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="Resources\Amazon\QuickDesigner2025\Test2025.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Resources\Temu\QuickDesigner2025\Test2025.csv">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="CsvHelper" Version="33.1.0" />
	  <PackageReference Include="Svg" Version="3.4.7" />
	  <PackageReference Include="WindowsAPICodePack.Shell.CommonFileDialogs.Wpf" Version="1.1.5.1" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\DesignerSuite.Core\DesignerSuite.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="Corel.Interop.VGCore">
	    <HintPath>C:\Program Files\Corel\CorelDRAW Graphics Suite 2019\Programs64\Assemblies\Corel.Interop.VGCore.dll</HintPath>
	  </Reference>
	</ItemGroup>
</Project>
